Problem: not updated to defi-wallet-core v0.3.1 (fix #297)
cronos-labs/play-cpp-sdk pull request #298
Opened 2022-12-06 13:38 UTC by leejw51crypto

Solution: update to latest

2022-12-07 02:26 UTC, leejw51crypto commented
working on windows build issue

2022-12-07 02:37 UTC, tomtau commented on .github/workflows/cpp-lint.yml
> +        compiler: [clang++-14]
it seems this matrix/environment isn't being used? the compiler is always hardcoded to 14 elsewhere?

2022-12-07 03:19 UTC, damoncro commented
Seems we are fixing the same issue: https://github.com/cronos-labs/play-cpp-sdk/pull/292?

2022-12-07 03:20 UTC, damoncro commented
But as I mentioned on https://github.com/cronos-labs/play-cpp-sdk/pull/292, `.github/workflows/cpp-lint.yml` should be removed, because the linter checked should be conducted after build.

2022-12-07 03:21 UTC, damoncro commented
You can check the failure details inside https://github.com/cronos-labs/play-cpp-sdk/actions/runs/3635125599/jobs/6133931849

2022-12-07 03:34 UTC, damoncro commented
I deleted cpp-linter.yml on https://github.com/cronos-labs/play-cpp-sdk/pull/292 to avoid linter issues (it is incorrect setup as I mentioned), please help review and merge before fixing the linter issue. So that we would be break the build because the linter issue.

2022-12-07 03:45 UTC, damoncro requested changes
Please check https://github.com/cronos-labs/play-cpp-sdk/pull/292 and merge it first.

2022-12-07 05:10 UTC, leejw51crypto commented
ok

2022-12-07 05:20 UTC, damoncro submitted a review, later dismissed

2022-12-07 05:25 UTC, leejw51crypto commented on .github/workflows/cpp-lint.yml
> +        compiler: [clang++-14]
yes, i'll remove it.

2022-12-07 06:23 UTC, tomtau commented
maybe tag defi-wallet-core v0.3.1 first?

2022-12-07 06:24 UTC, leejw51crypto commented
yes, i'm checking now

2022-12-07 07:08 UTC, leejw51crypto commented
rebasing now

2022-12-07 07:20 UTC, leejw51crypto commented
rebased

2022-12-07 09:49 UTC, damoncro commented
Please update https://github.com/cronos-labs/play-cpp-sdk/blob/main/play-cpp-sdk/Cargo.toml#L10 as well.

2022-12-07 12:44 UTC, leejw51crypto commented
ok

2022-12-08 01:21 UTC, tomtau approved these changes

2022-12-08 02:30 UTC, damoncro requested changes

2022-12-08 02:30 UTC, damoncro commented on play-cpp-sdk/Cargo.toml
> +version = "0.0.12-alpha"
Still missing
`defi-wallet-core-cpp = { path = "../defi-wallet-core-rs/bindings/cpp/", version = "0.3.1"}`
or
`defi-wallet-core-cpp = { path = "../defi-wallet-core-rs/bindings/cpp/", version = "0.3"}`
?

2022-12-08 04:09 UTC, damoncro requested changes

2022-12-08 04:09 UTC, damoncro commented on CHANGELOG.md
> +- Minting C++ Example : Encode,Send
Changes on play-cpp-sdk itself are needed to add:
- Replace custom cxx-build with official cxx-build
- Added the walletconnect registry API support
- Add app token for sepgrep CI
- Fix Walletconnect request deadlock issue
- Upgrade ethers to 1.0

2022-12-08 07:11 UTC, leejw51crypto commented on play-cpp-sdk/Cargo.toml
> +version = "0.0.12-alpha"
ok

2022-12-08 07:13 UTC, leejw51crypto commented
update changelog

2022-12-08 09:26 UTC, elecming approved these changes

2022-12-08 13:18 UTC, merged