Problem: no persistence of WalletConnect session state (fix #3)
cronos-labs/play-cpp-sdk pull request #34
Opened 2022-03-30 13:17 UTC by leejw51crypto

Solution: add callback for session state
- set_callback  to receive directly
- run_callback to receive through callback function

2022-03-31 02:00 UTC, tomtau reviewed
how will the caller be able to restore the session information after shutting down process and starting it up later: https://github.com/crypto-com/game-sdk-extras/blob/main/wallet-connect/src/client/session.rs#L18 ?

For example, how will it know what addresses the wallet provided? The state message sent in callbacks seems to only contain Uri which has a part of the information (secret key, bridge server URL, handshake topic...), but not all -- i.e. the caller can't save/persist the session state?

2022-03-31 02:00 UTC, tomtau commented on wallet-connect/src/client.rs
> +pub enum ClientState {
what about if the client state gets simply updated -- e.g. the user changes the default address or network in the wallet?

2022-03-31 02:42 UTC, leejw51crypto commented on wallet-connect/src/client.rs
> +pub enum ClientState {
ClientState is for delivering data through channel(read only), so user notified with ClientState.

working on these
1. save & load session(restroing from serialization) , user can store anywhere
2. in apply update in session, deliver session info to the user via callback, user refreshes, and maybe save again.
3. after restoring session, and ensure_session will work as it is, (in next try, shutdown current one, start the program again)
so it's persistent, user just use revived session to await for signature.

2022-03-31 06:15 UTC, leejw51crypto commented on wallet-connect/src/client.rs
> +pub enum ClientState {
added save , load session info, restoration added

but after restoration, signing not working. solving now.

2022-03-31 08:59 UTC, elecming commented on wallet-connect/examples/web3.rs
> +
It doesn't seem to work. When I disconnect, it throws error:

```
Error: missing field `approved`

Location:
    /Users/damonchen/Documents/game-sdk-extras/wallet-connect/src/client/socket.rs:181:30

```

2022-03-31 09:00 UTC, elecming commented on wallet-connect/examples/web3.rs
> +
And how to test the persistent session feature?

2022-03-31 09:07 UTC, leejw51crypto commented on wallet-connect/examples/web3.rs
> +
ok , i'll fix

2022-03-31 14:02 UTC, leejw51crypto commented
now, persistent, saved to session.info,
after successful signing, session.info is removed

and fix `approve` parsing error

2022-04-01 01:41 UTC, leejw51crypto commented
fixing ci errors

2022-04-01 02:03 UTC, tomtau requested changes
I think the persistence should work now, but two potential bugs:
1. removing handshake topics on restore
2. not notifying the client of wallet disconnection update due to duplicate data

There are also quite a few `clone` calls that may be possible to remove, but that's just a nit

2022-04-01 02:03 UTC, tomtau commented on wallet-connect/src/client.rs
> +    pub uri: Option<Uri>,
`uri` seems redundant? It can be reconstructed from the session info -- in the `Session`, there's a method `fn uri` which can construct it?

2022-04-01 02:03 UTC, tomtau commented on wallet-connect/src/client.rs
> +    sender: Option<UnboundedSender<ClientStateMessage>>,
maybe a different name or some comment for explanation what this sender is for, because there are other internal senders in the connector/socket etc.

2022-04-01 02:03 UTC, tomtau commented on wallet-connect/src/client/session.rs
> +            state: ClientState::Connected,
it may not be so -- see line 98... the update may be to be disconnected

2022-04-01 02:03 UTC, tomtau commented on wallet-connect/src/client.rs
> +    pub state: ClientState,
is this `ClientState` also redundant? `connected` is contained inside `SessionInfo`?

2022-04-01 02:03 UTC, tomtau commented on wallet-connect/src/client.rs
> +            newsender.send(msg).unwrap();
is it ok to unwrap?

2022-04-01 02:03 UTC, tomtau commented on wallet-connect/src/client/core.rs
> +        let handshake_topic = None;
I'm not sure why this is needed? `Uri` remains the same from the previously restored session -> the handshake topic should be the same.

just for reference, the original reference code (it seems it just switched to ethers as well) has persistence and doesn't invalidate handshake topics: https://github.com/nlordell/walletconnect-rs and there isn't anything about it in the technical spec

2022-04-01 02:03 UTC, tomtau commented on wallet-connect/src/client/session.rs
> +            callback.send(msg).unwrap();
safe to unwrap?

2022-04-01 05:55 UTC, leejw51crypto commented on wallet-connect/src/client.rs
> +    pub uri: Option<Uri>,
ok

2022-04-01 05:56 UTC, leejw51crypto commented on wallet-connect/src/client.rs
> +    sender: Option<UnboundedSender<ClientStateMessage>>,
ok, i'll change the name

2022-04-01 05:56 UTC, leejw51crypto commented on wallet-connect/src/client/session.rs
> +            state: ClientState::Connected,
ok

2022-04-01 05:57 UTC, leejw51crypto commented
> I think the persistence should work now, but two potential bugs:
> 
> 1. removing handshake topics on restore
> 2. not notifying the client of wallet disconnection update due to duplicate data
> 
> There are also quite a few `clone` calls that may be possible to remove, but that's just a nit

tried to use same topic, but user approval never delivered, but next try, it's delievered.
so changed to invalidate old handshake topic.

2022-04-01 05:58 UTC, leejw51crypto commented on wallet-connect/src/client/session.rs
> +            callback.send(msg).unwrap();
it's unbounded channel, never fails, so i'll change expect ,and comment

2022-04-01 06:00 UTC, leejw51crypto commented on wallet-connect/src/client/core.rs
> +        let handshake_topic = None;
yes, i'll check again. 
somehow persistent handshake not working correctly, user approval not delivered.
possibly, once subscribed, and disconencted, and that topic now invalidated inside wallet connect bridge, so next try with the same topic, not working?

2022-04-01 06:00 UTC, leejw51crypto commented on wallet-connect/src/client.rs
> +            newsender.send(msg).unwrap();
yes, it's ok to unwrap or expect.

2022-04-01 06:01 UTC, leejw51crypto commented on wallet-connect/src/client.rs
> +    pub state: ClientState,
i'll change the name, it's for channel message packet.

2022-04-01 06:01 UTC, leejw51crypto commented
working on the feedback

2022-04-01 06:06 UTC, leejw51crypto commented on wallet-connect/src/client/core.rs
> +        let handshake_topic = None;
but in that case, when i rerun web3 example, pending metamask worked

2022-04-01 06:08 UTC, tomtau commented on wallet-connect/src/client.rs
> +            newsender.send(msg).unwrap();
but why? can a comment be added why it is safe?

2022-04-01 06:10 UTC, tomtau commented on wallet-connect/src/client/core.rs
> +        let handshake_topic = None;
> user approval not delivered.

I think that's the correct behaviour -- for the persisted session, if it was approved before, it shouldn't need another approval... so persistence, it's ok to save it and assume the state is as before (unless some other update is sent later).
i.e. no need to trigger another approval on each restore... restore should just load the previous session state cached on disk/internal storage

2022-04-01 06:11 UTC, tomtau commented
> tried to use same topic, but user approval never delivered

that's expected and that's the correct behaviour: https://github.com/crypto-com/game-sdk-extras/pull/34#discussion_r840262234

2022-04-01 06:13 UTC, leejw51crypto commented on wallet-connect/src/client/core.rs
> +        let handshake_topic = None;
yes, but it's not approved state, metamask want to sign, but approve page doesn't appear. pending.

i stopped program in qrcode waiting, and ran again.

2022-04-01 06:16 UTC, tomtau commented on wallet-connect/src/client/session.rs
> +            callback.send(msg).unwrap();
https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.UnboundedSender.html#method.send

> If the receive half of the channel is [close](https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.UnboundedReceiver.html#method.close)d, either due to close being called or the [UnboundedReceiver](https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.UnboundedReceiver.html) having been dropped, this function returns an error. The error includes the value passed to send.

it can fail -- if the developer who added the callback is not careful and closes or drops the receiver...

2022-04-01 06:19 UTC, tomtau commented on wallet-connect/src/client/session.rs
> +            callback.send(msg).unwrap();
but I guess if this is hidden from C++ bindings, i.e. C++ bindings always initialise and maintain this stuff correctly, it should be ok

2022-04-01 07:27 UTC, leejw51crypto commented on wallet-connect/src/client/session.rs
> +            callback.send(msg).unwrap();
ok, i'll add code in case send fails. and add  comment

2022-04-01 07:31 UTC, leejw51crypto commented on wallet-connect/src/client.rs
> +            newsender.send(msg).unwrap();
i mean, when there are enough memory, and receiver is valid, send will succeed,
and when it fails, it would be process panic state.(out-of-memory etc)

https://docs.rs/futures/0.1.31/futures/sync/mpsc/fn.unbounded.html

I'll add comment

2022-04-01 07:45 UTC, tomtau commented on wallet-connect/src/client/core.rs
> +        let handshake_topic = None;
do you mean if you shutdown the program while the session state was pending a connection? If that's what you mean, it's better not to save/persist the pending state -- only save/persist the established ones

2022-04-01 08:31 UTC, tomtau commented
@leejw51crypto should the client state also store the last/next request ID? Currently, it's an atomic int that gets incremented with every request (i.e. not random)... so when the client is restored, it'll start requests with the IDs that were used for requests before. it's likely fine, but not sure if the bridge server or wallets will have any issue if a duplicate ID is used.

one alternative may also be to generate random IDs instead of incremental

2022-04-01 08:54 UTC, leejw51crypto commented
i'll try to include request-id to serialization. check whether it works as expected.

2022-04-02 11:00 UTC, leejw51crypto commented on wallet-connect/src/client/core.rs
> +        let handshake_topic = None;
yes , no saving  pending state.(just connected, not connected)
once connected, next time, directly goes to personal_sign

2022-04-04 01:40 UTC, leejw51crypto commented
added user control (get uri, sessioninfo) for c++ bindings (gamefi)
also that info delivered via callback, too.

2022-04-04 02:56 UTC, tomtau requested changes
duplicating the request id Information doesn't seem worth it -- I suggest one of the following:
1. just keep the atomic request id counter as now
2. remove the atomic request id counter and just keep the counter inside session (under the lock)
3. not have id counter, and just use random ids

2022-04-04 02:56 UTC, tomtau commented on wallet-connect/src/client.rs
> +    }
this doesn't give the QR code, but just the connection string (that can be displayed as a QR code)... so the name may be a bit confusing

2022-04-04 02:56 UTC, tomtau commented on wallet-connect/src/uri.rs
> +    }
this seems to be a bit redundant ? one can just call `as_url().to_string()`?

2022-04-04 02:56 UTC, tomtau commented on wallet-connect/src/client/session.rs
> +    pub last_request_id: Option<u64>,
the point of having `current_request: AtomicU64,` in `Connector` was that one can access the request id without locking the session... putting a duplicate request id in session will remove this point

2022-04-04 22:34 UTC, leejw51crypto commented on wallet-connect/src/client.rs
> +    }
ok, i'll change the name

2022-04-04 22:34 UTC, leejw51crypto commented on wallet-connect/src/uri.rs
> +    }
ok, i'll add as comment

2022-04-04 22:37 UTC, leejw51crypto commented
removed request id from session, restore back 
use random id in starting (full random u64 no response from server, applied % operation with 4 bytes unsigned range)
renaming

2022-04-04 22:55 UTC, leejw51crypto commented on wallet-connect/src/client/session.rs
> +    pub last_request_id: Option<u64>,
i see, i'll remove request-id from session, random will be used instead of 1 .
(to prevent duplicate id)

2022-04-06 03:49 UTC, tomtau requested changes
look all right, but it seems the implementation is just doing the random initialisation, but the requests are still incremental... I think if random, it can be random everywhere: so `current_request` field could be removed, and things like https://github.com/crypto-com/game-sdk-extras/blob/f3e428435a8b8fb5afb2a7e3bf5be653c114d3f8/wallet-connect/src/client/core.rs#L181 `self.current_request.fetch_add(1, Ordering::SeqCst);` can be replaced with generating a random id

2022-04-06 03:49 UTC, tomtau commented on wallet-connect/src/client/core.rs
> +        random_request_id %= 4_294_967_295;
I think the bridge server is implemented in JS, so it may be due to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

so perhaps just generate u32 and cast it to u64?

2022-04-06 03:49 UTC, tomtau commented on wallet-connect/src/client/core.rs
> +        random_request_id %= 4_294_967_295;
also as the comment says: "// Trust Wallet requires a non-zero request id" -- perhaps add one to make sure it's non-zero?

2022-04-06 03:49 UTC, tomtau commented on wallet-connect/src/client/core.rs
> +            current_request: AtomicU64::new(random_request_id),
no need to keep track of this if it's randomly generated... the requests can just generate the id by random, not by accessing this value

2022-04-06 03:49 UTC, tomtau commented on wallet-connect/src/client/core.rs
> +        println!("getting random id");
no need to print?

2022-04-06 03:49 UTC, tomtau commented on wallet-connect/src/client/session.rs
> +        let msg = ClientChannelMessage {
those messages can be constructed inside `if let`?

2022-04-06 04:38 UTC, leejw51crypto commented on wallet-connect/src/client/core.rs
> +            current_request: AtomicU64::new(random_request_id),
ok

2022-04-06 04:38 UTC, leejw51crypto commented on wallet-connect/src/client/core.rs
> +        println!("getting random id");
i'll remove it, it's debugging code

2022-04-06 04:38 UTC, leejw51crypto commented on wallet-connect/src/client/core.rs
> +        random_request_id %= 4_294_967_295;
ok

2022-04-06 04:46 UTC, leejw51crypto commented on wallet-connect/src/client/session.rs
> +        let msg = ClientChannelMessage {
i'll check

2022-04-06 09:47 UTC, leejw51crypto commented
changed to use random request id,
and non zero , more bandwidth

2022-04-07 01:43 UTC, tomtau reviewed
ok -- just for the updates... sometimes the update isn't about disconnection, but about changing a network or adding new addresses -- in which case, it's still connected

2022-04-07 01:43 UTC, tomtau commented on wallet-connect/src/client/session.rs
> +                state: ClientChannelMessageType::Disconnected,
Should the value here depend on `self.info.connected`?

2022-04-07 03:10 UTC, leejw51crypto commented on wallet-connect/src/client/session.rs
> +                state: ClientChannelMessageType::Disconnected,
yes, its connecting status is dependent on update.approved.
  ```
  self.info.connected = update.approved;
  ```
  
  i'll change to use `update.approved` 
approved -> call `Connected` 
not approved -> call `Disconnected`

2022-04-07 04:45 UTC, leejw51crypto commented on wallet-connect/src/client/session.rs
> +                state: ClientChannelMessageType::Disconnected,
changed update(), now it dispatch by the connected status,

and fixed the test,(get_tokens contract information changed)

2022-04-07 06:19 UTC, merged